# base
base_env: development

# for mysql
database_yml: conf/database.yml

# for create dummy data
log_echo: true
log_dir: log
log_level: Logger::INFO

tables_yml: conf/tables.yml
values_dir: resource/values

